### ISSUE TITLE
Textures are not loaded on Minecraft 1.19 Fabric

### ISSUE THREAD

**Issue by lospejos** [haykam821/Wooden-Hoppers#8]
I have `Minecraft 1.19` using Fabric and `woodenhoppers-1.3.0` mod installed.

When I find `hopper` in REI screen, I see items without textures, see screenshot below.

![image](https://user-images.githubusercontent.com/4608475/174341188-f35b8771-32a9-4a10-a3e8-7453a85daa00.png)

I also didn't find any images in `woodenhoppers-1.3.0.jar` file (is this expected?).

Please assist.

**Comment by haykam821** [comment]
This looks like the same issue as haykam821/Golden-Hoppers#17, where data generation wasn't run.

**Comment by haykam821** [comment]
[Version 1.3.1](https://github.com/haykam821/Wooden-Hoppers/releases/tag/1.3.1) should include generated data.
